import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/app/(Components)/Sidebar/side";
import Navbar from "@/app/(Components)/Navbar/nav";
import { ThemeProvider } from "next-themes";
// import { Zilla_Slab } from "next/font/google";

// const zillaSlab = Zilla_Slab({
//   subsets: ["latin"],
//   weight: ["400", "700"],
//   variable: "--font-zilla-slab", // Use CSS custom property
//   fallback: ["serif"],
//   display: "swap",
//   preload: true, // Preload the font
// });

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by Vordx technologies",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="antialiased flex font-zilla-slab">
        <ThemeProvider 
          attribute="class" 
          defaultTheme="system" // Allow system preference
          enableSystem={true}
          disableTransitionOnChange={false}
        >
          <Sidebar />
          <div className="flex-1 flex flex-col min-h-screen overflow-hidden">
            <Navbar />
            <main className="flex-1 overflow-auto p-4">
              {children}
            </main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}